services:
  - type: web
    name: your-app-name
    env: php
    buildCommand: |
      apt-get update
      apt-get install -y libpq-dev
      docker-php-ext-install pdo_pgsql
      composer install
      php artisan config:clear
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
